### ISSUE TITLE
Using with secureboot

### ISSUE THREAD

**Issue by Ramblurr** [jdoss/wireguard-dkms#1]
Hi there, thanks for providing a wireguard package for Fedora.

I'd  rather not disable secure boot on my system.  Do you know of a way to sign the kernel module in your package with my own key without building the entire package from source?

**Comment by jdoss** [comment]
The `wireguard-dkms` RPM uses DKMS to build the kernel module from source on your computer. There is no way to use it with secure boot without creating your own key and signing it after it has been built. Upstream fedora doesn't support kernel modules like WireGuard, so this is why it is not included and signed with the fedora key. 

TL; DR is disable secure boot or sign every WireGuard kernel module created by the `wireguard-dkms` package.

**Comment by Ramblurr** [comment]
Hi @jdoss, thanks for the reply. I understood your entire first paragraph before making this issue. I guess I didn't explain my self clearly, sorry for the misunderstanding.

> ... or sign every WireGuard kernel module created by the wireguard-dkms package.

My question is how to do exactly that, given that I already have my own signing key ready, and that I'd like to integrate it with the .src.rpm.

I am hoping there is a way to modify the .src.rpm such that I could build the .src.rpm and have it signed at build time, rather than installing the package and signing the installed ko manually.

**Comment by jdoss** [comment]
@Ramblurr Since the module is handled by DKMS if you wanted to build your own srpm that had extra steps to sign the module you would do it after the build step. 

```
%post
dkms add -m %{dkms_name} -v %{version} -q --rpm_safe_upgrade
dkms build -m %{dkms_name} -v %{version} -q
dkms install -m %{dkms_name} -v %{version} -q
```

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-signing-kernel-modules-for-secure-boot should have all the steps you need for doing this. 

Shoehorning this into your own custom RPM might be more work than installing the RPM letting it fail the `dkms install` step and then signing the module manually and then running `dkms install` but you do you. :smile:

**Comment by gaia** [comment]
I signed the module successfully. When I try to install, it tells me it is already installed:

```
> dkms install -m wireguard -v 0.0.20180531
Module wireguard/0.0.20180531 already installed on kernel 4.4.0-128-generic/x86_64
```

Should I be worried about this?

```dkms status
wireguard, 0.0.20180531, 4.4.0-128-generic, x86_64: installed (WARNING! Diff between built and installed module!)```

**Comment by jdoss** [comment]
That warning shouldn't be something you should worry about. It is complaining about the fact that the DKMS built module and the signed module do not match up. As long as it is loading, you should be fine.
